### ISSUE TITLE
Lummander with Luajit

### ISSUE THREAD

**Issue by dlannan-fmad** [Desvelao/lummander#3]
Im using Lummander with Luajit and I have embedded luafilesystem into my Luajit process, but there seems to be an issue with some of the script. In particular are:
```
local ftable = require("f.table")
local fstring = require("f.string")
```
There isnt any f folder included in the repo, and Im not sure if this is intended to reference lfs? 
Can you provide any ideas about this? Id really like to try out lummander.

**Comment by Desvelao** [comment]
Hi @dlannan-fmad , thank you so much for your interest!

You can get `lummander` if you use **Luarocks** (https://luarocks.org/modules/Desvelao/lummander) but maybe you can get to do it work in Luajit too. 

The `f.table` and `f.string` require statements do reference to `f` package.

lummander has these dependencies:
- `luafilesystem>=1.7.0`
- `chalk>=0.1.0`
- `f>=0.1.0`

To get the rest of the dependencies:
- `chalk` (v0.1.0) https://github.com/Desvelao/chalk/tree/v0.1.0
- `f` (v0.1.0) https://github.com/Desvelao/f/tree/v0.1.0

These packages are available in Luarocks too:
- `chalk` https://luarocks.org/modules/Desvelao/chalk
- `f` https://luarocks.org/modules/Desvelao/f

I created a CLI app using `lummander` that you could to be interested in check to see how to use it. It's a wrapper of some commands I use in the terminal. The app is called [lum](https://github.com/Desvelao/lum/tree/master/lum) and it is an hobby project I did to use `lummander`.

Best regards.

**Comment by dlannan-fmad** [comment]
Hi, thats awesome. Thanks. That explains the missing references :)
Im trying out lummander in a bootable system: https://github.com/dlannan/ljos
luarocks isnt needed for this. 
Will let you know how it turns out. Thanks again for the response.

edit: I'll have a look at lum too. Have been using luajit for a decade now and I think a nice little OS based on it, would be useful :)

**Comment by dlannan-fmad** [comment]
Its working great. Thanks for you help, really appreciate your software.
I havent spent too much time looking at lum, but it might be something that will work better than my console parser (which is quite simple and rudimentary). 
![2020-10-23_23-52](https://user-images.githubusercontent.com/60128766/97061476-8c8e6f80-15de-11eb-8e03-bf18a480700d.png)
