### ISSUE TITLE
Error: Parse error processing dependency 'f>=0.1.0'

### ISSUE THREAD

**Issue by elGabe** [Desvelao/lummander#4]
Hi!

I tried installing lummander on a fresh install of lua and luarocks and it gave me this error. Luarocks installed other libraries just fine so I was wondering if there might be something specific to lummander I might be missing?

**Comment by Desvelao** [comment]
Hi @elGabe ,

What versions of Lua and Luarocks did you installed? What Operating System are you using? [Here](https://github.com/daurnimator/lua-http/issues/135), there is an issue with the error you mention, it seems to be related to an old version of Luarocks.

`f` is a `lummander` dependency. You can find it in [luarocks](https://luarocks.org/modules/Desvelao/f). If you don't get to install it using Luarocks, you could get it from the [Github repository](https://github.com/Desvelao/f/tree/v0.1.0)

I hope this can help you.

**Comment by Desvelao** [comment]
I will close this issue due to inactivity.
