### ISSUE TITLE
is it possible to make an option required ?

### ISSUE THREAD

**Issue by amirhossein-ka** [Desvelao/lummander#5]
hello 
i want to get input like this `./myapp command -c <input>`
is it possible to make this option required or i need to get it from command ?

**Comment by Desvelao** [comment]
Hi @amirhossein-ka ,

The options can't be required.

You have some workarounds:
- Don't use an option for the required argument.
You could use some command schema as: `command <input>`. The `parsed.input` in the action function will contain the command.

Command definition:
- Using the `lummander` instace (`cli` in the example)
```lua
cli:command("command <input>", "My command description")
    :action(function(parsed, command, app)
        print("My command input is" .. parsed.input)
    end)
```
or use some variations mentioned [here](https://github.com/Desvelao/lummander#a-add-command-using-lummander-instance-methods)

Object command definition in file:
```lua
return {
	command = "command <input>",
	description = "My command description",
	action = function(parsed, command, lum)
		 print("My command input is" .. parsed.input)
	end
}
```

- Configure `-c` as an option and returns a message early if this option is not set in the command `action` function

Command definition:
- Using the `lummander` instace (`cli` in the example) and using its methods
```lua
cli:command("command", "My command description")
    :option(
        "command","c","Command option description",nil,"normal",nil)
    :action(function(parsed, command, app)
        if (not parsed.command) then return print("The --command/-c flag is required") end
        ....
    end)
```
or use some variations mentioned [here](https://github.com/Desvelao/lummander#a-add-command-using-lummander-instance-methods)

Object command definition in file if you load commands from files as explained [here](https://github.com/Desvelao/lummander#b-add-commands-from-a-directory):
```lua
return {
	command = "command",
	description = "My command description",
	options = {
		{short = "c", long = "command", description = "Command option description", type = "normal"}
	},
	action = function(parsed, command, lum)
		if (not parsed.command) then return print("The --command/-c flag is required") end
                ....
	end
}
```
